### ISSUE TITLE
Contribute to org-velocity?

### ISSUE THREAD

**Issue by ruricolist** [Fuco1/org-velocity#1]
I'm the original madman -- the author of org-velocity. With your permission, I'd like to merge some of your changes into the official version of org-velocity, which is overdue for an update.

**Comment by Fuco1** [comment]
Feel free. Is your code somewhere online, so in the future I can maybe send pull requests there? I wasn't able to find a repo.

Madman or not, we all do what works for us. As an emacs user, I understand that perfectly ;) (and I like to complain a lot, but it was all half in jest, so I apologise if it came out wrong)

**Comment by ruricolist** [comment]
I put up a development repository at https://github.com/ruricolist/org-velocity. You'll see it's a little improved from the version in contrib.

**Comment by Fuco1** [comment]
Nice. I'll rename this repo and fork your project.

Which changes do you want to pull? I might help with the merging if I find the time.

**Comment by ruricolist** [comment]
`delete-other-windows` is already gone. 

I definitely want to incorporate the code to clean up the preview. 

Jumping to the first result, and visiting the original buffer directly, can go in behind customizations, but the default behavior should stay the same. 

You're not the first person to complain that org-velocity only returns top-level headings. I mostly use org-velocity with very "flat" files, where only the top-level headings are of interest, so that's what I originally designed for. In the development version, there's a new variable (`org-velocity-heading-level`) to control the maximum depth to return headings at. I've extended it so a value of 0 means "match at any level." Does that cover your use case?
