### ISSUE TITLE
Error in post-command-hook (org-velocity-update): (search-failed "^\\* ")

### ISSUE THREAD

**Issue by bard** [Fuco1/org-velocity#2]
I'm getting this error intermittently. It usually happens 2-5 times, causing no matches to show, then things start to work normally. Emacs version: 24.4.1. Anything I can do to further debug?

**Comment by Fuco1** [comment]
I haven't yet switched to 24.4 so it is most likely related to that. I can't tell you more now.  You can activate the debugger and step through the functions to see where it fails.

**Comment by bard** [comment]
Debugger is already activated but unfortunately isn't triggered for errors in `post-command-hook`.

Just found out: issue stops if I manually read the bucket file into a buffer before calling org-velocity-read. I'll use it as a workaround for now.
